In [1]:
from pathlib import Path
from src.pew_worker import PewWorker

# The notebook runs from the project root
PROJECT_ROOT = Path.cwd()

print("Project root:", PROJECT_ROOT)

Project root: c:\Users\sybun\OneDrive\Desktop\Python Projects Class\Machine Learning Programming\lab2_tidying_cleaning_imputation_outlier

In [2]:
# Locate CSV files in the data directory
pew_files = sorted((PROJECT_ROOT / "data").rglob("*.csv"))

print("CSV files found:", len(pew_files))
for file in pew_files:
    print(file.name)

CSV files found: 1
Pew Research Center Global Attitudes Spring 2025 Dataset CSV.csv

In [3]:
# Create the PEW worker and load the dataset
pew = PewWorker(pew_files[0])
pew_df = pew.load()

print("Dataset shape:", pew_df.shape)
display(pew_df.head())

Dataset shape: (28333, 483)

,survey,country,weight,id,econ_sit,satisfied_democracy,polsys_satisfied,fav_us,fav_china,fav_eu,...,region_skorea,region_spain,region_sweden,region_turkey,region_uk,urbanicity,qdate_s,qdate_e,intdate_aus,phone_sample
0,1202501,2,0.592005,8001432,2,2,,4,3,2,...,,,,,,,3/23/2025,3/23/2025,,1
1,1202501,2,0.446814,8003472,4,3,,4,4,2,...,,,,,,,3/11/2025,3/11/2025,,1
2,1202501,2,1.120110,8006468,2,1,,3,8,2,...,,,,,,,4/1/2025,4/1/2025,,1
3,1202501,2,0.695317,8006970,2,1,,4,8,1,...,,,,,,,3/10/2025,3/10/2025,,1
4,1202501,2,0.369352,8008601,2,2,,4,3,1,...,,,,,,,3/23/2025,3/23/2025,,1

In [4]:
# Reshape the income data
pew_melted = pew.melt_income()

print("Reshaped dataset:", pew_melted.shape)
display(pew_melted.head())

# Summarize nonblank responses by income variable
pew_summary = pew.summary()

print("Summary columns:", pew_summary.columns.tolist())
display(pew_summary.head(10))

Reshaped dataset: (1388317, 436)

,survey,country,weight,id,econ_sit,satisfied_democracy,polsys_satisfied,fav_us,fav_china,fav_eu,...,region_sweden,region_turkey,region_uk,urbanicity,qdate_s,qdate_e,intdate_aus,phone_sample,income,count
0,1202501,2,0.592005,8001432,2,2,,4,3,2,...,,,,,3/23/2025,3/23/2025,,1,d_income_argentina,
1,1202501,2,0.446814,8003472,4,3,,4,4,2,...,,,,,3/11/2025,3/11/2025,,1,d_income_argentina,
2,1202501,2,1.120110,8006468,2,1,,3,8,2,...,,,,,4/1/2025,4/1/2025,,1,d_income_argentina,
3,1202501,2,0.695317,8006970,2,1,,4,8,1,...,,,,,3/10/2025,3/10/2025,,1,d_income_argentina,
4,1202501,2,0.369352,8008601,2,2,,4,3,1,...,,,,,3/23/2025,3/23/2025,,1,d_income_argentina,

Summary columns: ['income', 'response_count']

                income  response_count
0  d_income2_argentina              99
1     d_income2_brazil              42
2     d_income2_canada             120
3     d_income2_france              52
4    d_income2_germany              71
5     d_income2_greece              28
6    d_income2_hungary              72
7      d_income2_india             198
8  d_income2_indonesia               3
9     d_income2_israel             137